### PR TITLE
Change version to 1.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://github.com/smallrye/smallrye-opentracing/issues/3#issuecomment-403428543

### CODE REVIEW

**Comment by pavolloffay** [comment]
I can do that in a separate PR. It's not related here.

Although, maybe I would like to release the first version as 0.1.0. @kenfinnigan would that work? Or does the release process expect the major version as 1?

**Comment by mkouba** [comment]
I would go with `1.0.0` and if you really think it's not stable enough then I would use some `Beta` qualifier...

**Comment by pavolloffay** [comment]
Not sure if the release process supports it. Using semver seems good enough to me.

**Comment by pavolloffay** [comment]
> @pavolloffay, as was mentioned in the SmallRye group, release numbering needs to align with MP Spec version, for major and minor.

I find this a bit limiting given that this is an implementation with its own lifecycle.

**Comment by kenfinnigan** [comment]
Why is it limiting?

The patch number can be incremented as much as is needed to cater for bug fixes, etc.

**Comment by pavolloffay** [comment]
The API here can break without breaking spec API.

**Comment by kenfinnigan** [comment]
What API can break?

Surely the only API this is implementing is the MP OT API.

**Comment by pavolloffay** [comment]
> Surely the only API this is implementing is the MP OT API.

Not completely true. I would say all impls contain some "glue" code - interceptors, DynamicFeatures which implementors use to enable MP in their containers.

**Comment by kenfinnigan** [comment]
So an SPI?

It's not ideal from an SPI perspective, but this is what was agreed in the list months ago. If we find it problematic we can always re-evaluate.

But initially the bigger concern was making it easy to know which version of an impl aligns with which version of a spec

**Comment by pavolloffay** [comment]
Ack, I wasn't up to date with this. Thanks for the explanation. It would be good to add it to the release process https://groups.google.com/forum/#!topic/smallrye/Ct4-k3L-JbA.

> So an SPI?

Not necessarily SPI, It's just implementation. 

> But initially the bigger concern was making it easy to know which version of an impl aligns with which version of a spec

This definitely helps. I would say the main consumers of the smallrye are vendors which probably pay attention to what version are they pulling it. To make this impl work let say in Thorntail requires to use/register the mentioned filters/interceptors which are not exposed via the spec but only by this impl, hence breaking change possible.

**Comment by kenfinnigan** [comment]
The discussion on versioning happened within https://groups.google.com/forum/#!topic/smallrye/4vuB5MjvNQk

**Comment by pavolloffay** [comment]
Thanks @kenfinnigan I will comment there.

**Pull request merged**
