### PR TITLE
Add initial implementation

### PR DESCRIPTION
**Pull request by pavolloffay**
Do not merge! 

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
One TCK which invokes async resource is failing https://github.com/eclipse/microprofile-opentracing/blob/master/tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java#L208. 

It fails because server span is not finished. It should be finished in `AsyncListener` https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/SpanFinishingFilter.java#L68. The `AsyncListener` is never invoked. The request in finally block in filter it's already marked as complete (private field). This was passing in Swarm correctly.

@kenfinnigan @mkouba do you know why the `AsyncListener` is not invoked? Can you point somebody from resteasy/undertow who might help?

**Comment by pavolloffay** [comment]
Is there a way to find out in filter that async request has been completed?
Is there a way to have a globally registered AsyncListener or some completion callbak?

**Comment by mkouba** [comment]
@pavolloffay Hm, is the filter registered successfully?

**Comment by pavolloffay** [comment]
It is, otherwise, other TCKs would fail.

**Comment by pavolloffay** [comment]
Just referencing ML discussions related to the failing TCK, at the moment without resolution:
http://lists.jboss.org/pipermail/resteasy-dev/2018-July/000545.html 
https://issues.jboss.org/browse/UNDERTOW-1258 
http://lists.jboss.org/pipermail/undertow-dev/2018-July/002234.html

**Comment by pavolloffay** [comment]
Based on the discussion on ML, there seems to be a bug in the undertow. 

@mkouba @kenfinnigan to unblock work on this I would just temporarily skip this one test and track the progress in a separate issue.

**Comment by mkouba** [comment]
@pavolloffay +1; just exclude the test in `tck-suite.xml` and create a new github issue.

**Comment by pavolloffay** [comment]
Done, https://github.com/smallrye/smallrye-opentracing/issues/5, the link is also in the comment in `tck-suite.xml`.

Can somebody review/approve?

**Pull request merged**
